export interface CountryEducation {
  iso3: string
  history: string
  current: string
  economy: string
  knownFor: string[]
  challenges: string[]
  resources: string[]
}

export const COUNTRY_EDUCATION: Record<string, CountryEducation> = {
  KEN: {
    iso3: 'KEN',
    history: `Kenya's modern history begins with British colonisation in the late 19th century, formally declared a Crown Colony in 1920. The Mau Mau uprising (1952–1960) was a pivotal armed resistance movement against colonial rule that accelerated independence. Kenya gained independence on 12 December 1963, with Jomo Kenyatta as its first Prime Minister and later President. The post-independence era saw economic growth alongside political consolidation under KANU party dominance. Multiparty democracy was restored in 1991, followed by a landmark peaceful transition of power in 2002. Kenya's 2007–08 post-election violence, which killed over 1,000 people and displaced hundreds of thousands, led to a power-sharing agreement and constitutional reforms — culminating in a new constitution in 2010 that devolved significant power to 47 counties.`,
    current: `Kenya is East Africa's economic and financial hub, with one of the continent's most diversified and services-driven economies. Nairobi hosts the UN Environment Programme and UN-Habitat headquarters, reflecting its regional significance. The country has a vibrant tech startup ecosystem — dubbed "Silicon Savannah" — led by hubs like iHub. President William Ruto, elected in 2022, has championed a "bottom-up economic model" focused on the informal sector and SME growth. Kenya faces ongoing fiscal pressures with high public debt, and experienced significant anti-government protests in 2024 over proposed tax hikes, which the government subsequently withdrew.`,
    economy: `Kenya's GDP (~$120bn, 2024) is the largest in East and Central Africa. Services dominate at ~50% of GDP, led by finance, telecoms, and retail. Agriculture employs ~40% of the workforce; tea, coffee, cut flowers, and horticultural produce are the main exports. Tourism is a major foreign exchange earner. M-Pesa, launched by Safaricom in 2007, is Kenya's globally acclaimed mobile money platform, now used by 30M+ customers. Kenya is a net energy importer but has significant geothermal capacity — generating ~45% of its electricity from geothermal sources, making it one of the world's leading geothermal producers.`,
    knownFor: [
      'M-Pesa — the world\'s most successful mobile money platform',
      'Silicon Savannah tech startup ecosystem',
      'Nairobi as East Africa\'s financial and logistics hub',
      'World-class long-distance runners (Olympic and marathon champions)',
      'Masai Mara wildlife reserve and safari tourism',
      'Cut-flower exports — the world\'s third largest',
      'Geothermal energy leadership',
    ],
    challenges: [
      'High and rising public debt (>70% of GDP)',
      'Youth unemployment (~30%) despite strong GDP growth',
      'Inequality — Nairobi\'s Kibera is one of Africa\'s largest informal settlements',
      'Climate vulnerability — erratic rainfall affecting agriculture',
      'Corruption and governance quality concerns',
      'Security pressures from Al-Shabaab in the north',
    ],
    resources: [
      'Tea and coffee (primary agricultural exports)',
      'Geothermal energy (Olkaria fields)',
      'Titanium and soda ash mining',
      'Horticulture and cut flowers',
      'Tourism (wildlife, beaches, Great Rift Valley)',
      'Financial and logistics services for East Africa',
    ],
  },

  NGA: {
    iso3: 'NGA',
    history: `Nigeria's pre-colonial history includes powerful states and empires — the Benin Kingdom, Kanem-Bornu, and the Sokoto Caliphate. British colonisation began in the late 19th century and the country was amalgamated as a single administrative unit in 1914. Independence was gained on 1 October 1960, with a federal structure reflecting Nigeria's extraordinary ethnic and religious diversity (250+ ethnic groups; predominantly Muslim north, predominantly Christian south). A devastating civil war (the Biafra War, 1967–70) resulted in over one million deaths. Military coups dominated the next three decades, punctuated by short civilian interludes. Democratic civilian rule was re-established in 1999 and has continued unbroken since, with peaceful transfers of power in 2015 and 2023 — significant milestones in Africa's democratic record.`,
    current: `Nigeria is Africa's most populous nation (~220 million people) and largest economy by nominal GDP. It is the continent's biggest oil producer and a major player in global energy markets. President Bola Tinubu, inaugurated in May 2023, initiated significant economic reforms — removing the longstanding petrol subsidy and unifying the foreign exchange rate — which triggered sharp inflation and currency depreciation in the near term. The north faces serious security challenges: Boko Haram/ISWAP insurgency in the northeast, banditry in the northwest, and farmer-herder conflicts in the Middle Belt. The southeast sees periodic separatist agitation. Despite these pressures, Lagos remains Africa's most dynamic commercial city and startup hub.`,
    economy: `Nigeria's GDP (~$500bn, nominal) is Africa's largest, driven heavily by oil and gas (~90% of foreign exchange earnings). However, the oil sector employs only ~4% of the workforce — agriculture (employing ~36%) and services dominate actual economic activity. The informal economy is enormous, estimated at 57% of GDP. Lagos is home to Africa's most valuable tech startup ecosystem, including unicorns Flutterwave, Paystack (acquired by Stripe), and Interswitch. Nollywood — Nigeria's film industry — is the world's second-largest by volume and generates ~$1bn+ annually. Nigeria is a major exporter of cocoa and sesame seeds.`,
    knownFor: [
      'Africa\'s largest economy and most populous nation',
      'Oil and gas production (Niger Delta)',
      'Nollywood — the world\'s second largest film industry',
      'Africa\'s leading tech startup ecosystem (Lagos)',
      'Afrobeats music — global cultural influence',
      'Largest diaspora remittance recipient in Africa (~$20bn/yr)',
      'Diversity — over 250 ethnic groups and languages',
    ],
    challenges: [
      'Oil dependence and revenue volatility',
      'Boko Haram/ISWAP insurgency in the northeast',
      'Extreme inequality — a third of population in extreme poverty',
      'Infrastructure deficit (power, roads)',
      'Currency and inflation pressures post-2023 reforms',
      'Security: banditry, kidnapping, and communal violence',
    ],
    resources: [
      'Crude oil (Niger Delta) — Africa\'s largest reserves',
      'Natural gas (significant LNG export infrastructure)',
      'Agriculture: cocoa, sesame, groundnuts, palm oil',
      'Solid minerals: coal, iron ore, tin, limestone',
      'Bitumen deposits (largest in the world)',
      'Fisheries and maritime resources',
    ],
  },

  ETH: {
    iso3: 'ETH',
    history: `Ethiopia is one of the world's oldest nations and the only African country to have successfully resisted European colonisation — defeating Italy at the Battle of Adwa in 1896. The ancient Aksumite Empire (1st–7th century AD) was a major trading power; the Solomonic dynasty, claiming descent from King Solomon and the Queen of Sheba, ruled for centuries. Emperor Haile Selassie ruled from 1930 until a Marxist military junta (the Derg) deposed him in 1974. The Derg's brutal rule ended in 1991 when the Ethiopian People's Revolutionary Democratic Front (EPRDF) took power. The EPRDF implemented an ethnic federalism system across nine regional states. Prime Minister Abiy Ahmed came to power in 2018, winning the Nobel Peace Prize in 2019 for the Ethiopia-Eritrea peace deal. A devastating civil war in the Tigray region (2020–2022) killed hundreds of thousands and created one of the world's worst humanitarian crises.`,
    current: `Ethiopia is Africa's second most populous country (~125 million) and one of the continent's fastest-growing economies over the past decade. The country faces significant post-war reconstruction challenges in Tigray, Afar, and Amhara regions. Conflict has also spread to other areas, with Amhara regional forces clashing with federal troops since 2023. Despite these conflicts, Addis Ababa remains the diplomatic capital of Africa, hosting the African Union headquarters. Ethiopia is pursuing an ambitious industrialisation agenda through industrial parks and manufacturing investment, and has significant hydropower ambitions with the Grand Ethiopian Renaissance Dam (GERD) on the Nile.`,
    economy: `Ethiopia's economy is among Africa's fastest-growing, though it remains largely agriculture-based (~35% of GDP, ~70% of employment). Coffee is Ethiopia's most iconic export and cultural institution — it is the birthplace of coffee. Ethiopia is Africa's largest coffee producer. Flowers and vegetables are growing export industries. The government has pursued state-led industrialisation through large public investments and Chinese-financed infrastructure. The Grand Ethiopian Renaissance Dam, now partially operational, will make Ethiopia a major electricity exporter. Inflation has been a persistent challenge, exceeding 30% at times. Ethiopia joined the African Continental Free Trade Area and is seeking full WTO membership.`,
    knownFor: [
      'The only African nation to defeat a European colonial power (Battle of Adwa, 1896)',
      'Birthplace of coffee — Kaffa region',
      'The African Union headquarters (Addis Ababa)',
      'Ancient Aksumite civilisation and Orthodox Christianity',
      'Lucy — the 3.2 million year old hominin fossil found in Ethiopia',
      'Long-distance running — Olympic champions for six decades',
      'Grand Ethiopian Renaissance Dam (largest in Africa)',
    ],
    challenges: [
      'Ongoing armed conflicts in multiple regions',
      'One of the world\'s largest humanitarian crises (post-Tigray war)',
      'Landlocked status following Eritrean independence',
      'High inflation and hard currency shortages',
      'Climate vulnerability — droughts affecting food security',
      'Extreme poverty in rural areas',
    ],
    resources: [
      'Coffee (primary export, cultural identity)',
      'Hydropower (Blue Nile, GERD)',
      'Agriculture: teff, sesame, flowers, pulses',
      'Gold and tantalum mining',
      'Geothermal energy potential (Rift Valley)',
      'Livestock (Africa\'s largest livestock population)',
    ],
  },

  GHA: {
    iso3: 'GHA',
    history: `Ghana was the first sub-Saharan African country to gain independence from colonial rule, on 6 March 1957, led by Kwame Nkrumah — a pan-Africanist icon. The Gold Coast, as it was known under British rule, was so named for its historic role in the Atlantic gold trade. Ghana also played a central role in the transatlantic slave trade — Elmina and Cape Coast castles remain powerful historical sites. After independence, Nkrumah's socialist-led government was overthrown in a 1966 coup. A cycle of military and civilian governments followed until the Fourth Republic was established in 1993. Ghana is widely regarded as one of West Africa's most politically stable democracies, with consistent peaceful transfers of power since 1992. It served as a symbol of democratic maturity when opposition candidate John Atta Mills defeated the incumbent in 2008.`,
    current: `Ghana is considered one of West Africa's most stable and open economies and democracies. John Mahama won the 2024 presidential election, returning to power with a mandate focused on economic recovery. Ghana experienced a severe economic crisis in 2022–23 — inflation peaked at ~54%, the cedi lost ~60% of its value, and the country defaulted on external debt for the first time, seeking IMF support. A debt restructuring process is underway. Despite the fiscal crisis, Ghana's institutions held — there was no breakdown of democracy or social order. Oil was discovered offshore in 2007 (Jubilee Field) and production began in 2010, diversifying the economy.`,
    economy: `Ghana's economy (~$75bn GDP) is diversified relative to its neighbours — driven by gold, oil, cocoa, and growing services. It was the world's second-largest cocoa producer for many years. Gold mining employs hundreds of thousands and is a major foreign exchange earner. Offshore oil and gas production (from the Jubilee, TEN, and Sankofa fields) contributes ~20% of government revenue. Ghana has a relatively developed financial sector and a growing technology and fintech scene in Accra. It is the leading exporter of cashew nuts in West Africa. Tourism is growing, with the "Year of Return" campaign (2019) attracting the African diaspora.`,
    knownFor: [
      'First sub-Saharan country to gain independence (1957)',
      'Kwame Nkrumah — pan-African icon',
      'Gold and cocoa — historic "Gold Coast" export economy',
      'One of West Africa\'s most stable democracies',
      '"Year of Return" — major diaspora tourism campaign',
      'Cape Coast and Elmina slave trade castles',
      'Kente cloth — iconic woven textile tradition',
    ],
    challenges: [
      'Debt crisis and IMF programme (2022–23)',
      'High inflation and currency depreciation',
      'Over-dependence on commodity exports (gold, cocoa, oil)',
      'Illegal gold mining (galamsey) causing environmental damage',
      'Youth unemployment and graduate underemployment',
      'Infrastructure gaps outside Accra-Kumasi corridor',
    ],
    resources: [
      'Gold (major mining industry)',
      'Offshore oil and gas (Jubilee, TEN, Sankofa fields)',
      'Cocoa (world top-3 producer)',
      'Cashew nuts and shea butter',
      'Manganese and bauxite',
      'Timber and marine fisheries',
    ],
  },

  ZAF: {
    iso3: 'ZAF',
    history: `South Africa's history is defined by its complex layering of indigenous kingdoms, Dutch and British colonisation, and the apartheid system (1948–1994). The Dutch East India Company established a settlement at the Cape in 1652. The discovery of diamonds (1867) and gold (1886) transformed the region, fuelling the Anglo-Boer Wars. The apartheid regime — a system of legislated racial segregation and oppression — was formally institutionalised in 1948 by the National Party. The African National Congress (ANC), founded in 1912, led the liberation struggle, with figures such as Nelson Mandela, Walter Sisulu, and Oliver Tambo. Mandela spent 27 years in prison before his release in 1990. South Africa transitioned peacefully to democracy in 1994, with Mandela becoming the country's first democratically elected president — hailed globally as a miracle of reconciliation.`,
    current: `South Africa is Africa's most industrialised economy and its second-largest by GDP. It faces deep structural challenges: 32% unemployment (60%+ among youth), extreme inequality (one of the world's highest Gini coefficients), persistent load-shedding (rolling blackouts), high crime rates, and weakening state institutions. The ANC, which has governed since 1994, lost its parliamentary majority for the first time in May 2024 elections, forming a Government of National Unity with the Democratic Alliance and other parties. This political shift is being watched closely as a test of South Africa's democratic resilience. The country has one of Africa's most sophisticated financial markets and capital market infrastructure.`,
    economy: `South Africa's GDP (~$400bn) is the continent's second largest. The economy is diversified: mining (gold, platinum, coal, diamonds), manufacturing, financial services, retail, and agriculture. South Africa is the world's largest producer of platinum and chrome, and a top producer of gold, manganese, and vanadium. Johannesburg is Africa's financial capital. The automotive sector (BMW, Mercedes, Toyota all have manufacturing plants) is a significant industrial pillar. Severe energy shortages — Eskom's load-shedding — have cost an estimated 2–3% of GDP annually. Tourism is recovering post-COVID, drawn by the Cape region, wildlife, and wine industry.`,
    knownFor: [
      'Nelson Mandela and the end of apartheid',
      'World\'s largest platinum producer',
      'The Cape Winelands and Cape of Good Hope',
      'Kruger National Park and the Big Five',
      'Johannesburg as Africa\'s financial capital',
      'Rugby and cricket — consistent world-class performance',
      'Constitutional democracy with strong rights protections',
    ],
    challenges: [
      'One of the world\'s highest unemployment rates (~32%)',
      'Extreme inequality (Gini coefficient >0.60)',
      'Eskom load-shedding and energy crisis',
      'Very high rates of violent crime',
      'Corruption and state capture aftermath',
      'Skills emigration ("brain drain")',
    ],
    resources: [
      'Platinum group metals (world\'s largest reserves)',
      'Gold (Witwatersrand Basin)',
      'Coal (major electricity generation and export)',
      'Diamonds (Kimberley)',
      'Manganese, chromium, vanadium',
      'Agriculture: wine, citrus, maize, sugar',
    ],
  },

  TZA: {
    iso3: 'TZA',
    history: `Tanzania was formed in 1964 by the union of Tanganyika (independent 1961) and Zanzibar (independent 1963). Tanganyika was led to independence by Julius Nyerere, one of Africa's most respected leaders. Nyerere's socialist ujamaa ("familyhood") policy — including forced villagisation — had mixed results economically but promoted national unity and literacy. Zanzibar, with its Arab-Swahili history as a former Sultanate and hub of the Indian Ocean trade (and slave trade), maintains a distinct semi-autonomous identity within the union. Tanzania was the first East African country to abolish colonial-era wildlife hunting reserves and create national parks. The country maintained stability and peace throughout the Cold War era, hosting liberation movements from neighbouring countries. President Samia Suluhu Hassan, who took office in 2021 following the death of President John Magufuli, became Africa's first female head of state and has pursued a notably more open and reform-oriented approach.`,
    current: `Tanzania is East Africa's second-largest economy and among the continent's most politically stable nations. Under President Samia, Tanzania has re-engaged with international partners after a period of isolation, rejoined the East African Community's integration process, and taken a more pragmatic approach to foreign investment. The country is a leading destination for safari tourism (Serengeti, Ngorongoro) and has major new gas reserves offshore. A large-scale infrastructure push — including Standard Gauge Railway — is underway. Zanzibar is growing as a high-end tourism destination and has aspirations to become an Islamic finance hub.`,
    economy: `Tanzania's GDP (~$85bn) is driven by agriculture (~25% of GDP, ~65% of employment), tourism, and mining. Gold is the largest export earner; Tanzania is among Africa's top gold producers. Coffee, tea, cotton, cashews, and tobacco are key agricultural exports. Major natural gas discoveries offshore (the Ruvuma Basin holds some of East Africa's largest reserves) could transform the economy once an LNG export terminal is built — a project under negotiation with international energy companies. Tourism centres on the Serengeti, Ngorongoro Crater, Kilimanjaro, and Zanzibar beaches. Tanzania benefits from being an AGOA beneficiary for textile exports.`,
    knownFor: [
      'Serengeti — home to the Great Migration, the world\'s largest animal movement',
      'Mount Kilimanjaro — Africa\'s highest peak',
      'Zanzibar — spice island, ancient trading history',
      'Julius Nyerere — one of Africa\'s most revered leaders',
      'Ngorongoro Crater — world\'s largest intact volcanic caldera',
      'Significant offshore natural gas reserves',
      'Swahili language — Africa\'s most widely spoken indigenous language',
    ],
    challenges: [
      'Dependence on rain-fed agriculture and climate vulnerability',
      'Infrastructure gaps outside Dar es Salaam',
      'Semi-autonomous Zanzibar political tensions',
      'LNG development delays impacting fiscal projections',
      'Limited industrial diversification',
      'Population growth outpacing service delivery',
    ],
    resources: [
      'Gold (major export)',
      'Natural gas (Ruvuma offshore basin)',
      'Tourism (Serengeti, Kilimanjaro, Zanzibar)',
      'Agriculture: coffee, tea, cashews, sisal',
      'Gemstones: tanzanite (found only in Tanzania)',
      'Hydropower potential',
    ],
  },

  RWA: {
    iso3: 'RWA',
    history: `Rwanda's modern history is indelibly marked by the 1994 genocide, in which an estimated 800,000–1,000,000 Tutsi and moderate Hutu were killed in 100 days — one of the fastest mass killings in recorded history. Colonial powers (first Germany, then Belgium) hardened pre-existing social distinctions between Hutu, Tutsi, and Twa into a racialised hierarchy, laying the groundwork for ethnic violence that began in the lead-up to independence in 1962. The Rwanda Patriotic Front (RPF), a Tutsi-led rebel army led by Paul Kagame, halted the genocide and took control of the country in July 1994. Post-genocide Rwanda embarked on a remarkable reconstruction under Kagame's leadership — prioritising reconciliation (gacaca community courts), national identity over ethnicity, women's empowerment, and a vision of becoming a knowledge and services economy. Rwanda joined the Commonwealth in 2009, despite having no colonial ties to Britain.`,
    current: `Rwanda is often cited as Africa's governance model for its low corruption, clean cities, effectiveness of public service delivery, and gender representation — the parliament has the world's highest share of female legislators (~61%). President Paul Kagame has won re-election with very large majorities; critics point to restrictions on political opposition and press freedom. The country is positioning itself as a regional hub for conferences, finance, and technology — Kigali hosts major international summits and has a world-class convention centre. Rwanda faces pressure from its involvement in eastern DRC, where it is alleged to support the M23 rebel group — a source of significant international tension.`,
    economy: `Rwanda's economy (~$14bn GDP) is small but growing rapidly (~8% per year pre-COVID). Services — particularly tourism, finance, and hospitality — are the fastest-growing sectors. Gorilla trekking in Volcanoes National Park draws high-value, low-volume tourism. Coffee and tea are primary agricultural exports. Rwanda has made significant strides in financial inclusion (through mobile money and banking expansion) and ease of doing business. The country aspires to become the "Singapore of Africa" — a small, efficient, well-governed hub economy. It has attracted investment from major international companies including Volkswagen (vehicle assembly) and Andela. The national carrier, RwandAir, is growing as an African aviation hub.`,
    knownFor: [
      'Fastest post-genocide reconstruction in modern history',
      'World\'s highest share of female parliamentarians (~61%)',
      'Cleanest and safest city in Africa (Kigali)',
      'Mountain gorilla conservation (Volcanoes National Park)',
      'Near-zero tolerance for corruption — consistently top African governance rankings',
      'Umuganda — monthly community work days',
      '"Singapore of Africa" governance ambitions',
    ],
    challenges: [
      'Small, landlocked economy highly dependent on aid',
      'Limited natural resources',
      'Restricted political space and press freedom',
      'Regional tensions over DRC/M23 involvement',
      'High population density (most densely populated mainland African country)',
      'Climate vulnerability — hillside erosion and landslides',
    ],
    resources: [
      'Tourism (gorillas, Lake Kivu, cultural heritage)',
      'Coffee and tea (high-quality specialty exports)',
      'Coltan and cassiterite (conflict mineral challenges)',
      'Methane gas (Lake Kivu — unique energy source)',
      'Human capital and services economy',
      'Financial and logistics hub services',
    ],
  },

  SEN: {
    iso3: 'SEN',
    history: `Senegal has been a crossroads of trans-Saharan trade routes, Islamic scholarship, and Atlantic commerce for centuries. The city of Saint-Louis, founded by the French in 1659, was the first European settlement in sub-Saharan Africa. Senegal gained independence from France on 4 April 1960 under Léopold Sédar Senghor, a poet, philosopher, and one of Africa's most intellectually distinguished leaders — also the first African elected to the Académie française. Senghor voluntarily transferred power to Abdou Diouf in 1980 — a rare act of voluntary presidential transition in Africa at the time. Senegal has maintained unbroken democratic governance since independence, making it one of Africa's most stable countries. The Casamance region in the south has experienced a low-level separatist conflict since 1982, though recent peace agreements have largely held.`,
    current: `Senegal is West Africa's most enduring democracy and a model of political stability — having peacefully transferred power multiple times. In March 2024, Bassirou Diomaye Faye won a historic presidential election, becoming the youngest head of state in Senegalese history (and one of the youngest in Africa) on an anti-corruption and sovereignty platform. Faye and Prime Minister Ousmane Sonko represent a generational shift, with promises to renegotiate natural resource contracts and reduce dependence on France. Senegal is on the cusp of a major economic transformation with large offshore oil and gas reserves (Sangomar field, GTA project) beginning production in 2024 — the first time Senegal will produce hydrocarbons at scale.`,
    economy: `Senegal's GDP (~$30bn) has grown consistently at 5–7% annually. The economy is diversified: remittances (~10% of GDP), services (telecommunications, finance), fishing, phosphate mining, and tourism. Dakar is the most important financial and services hub in francophone West Africa. The CFA franc monetary union ties Senegal's currency to the euro — a source of both stability and debate. Agriculture (groundnuts, millet, sorghum) employs ~60% of the rural population. Offshore oil from the Sangomar field and gas from Greater Tortue Ahmeyim LNG are expected to significantly boost government revenues from 2025 onwards, raising both opportunity and governance challenges.`,
    knownFor: [
      'Africa\'s oldest continuous democracy (independence without military coup)',
      'Léopold Sédar Senghor — poet, philosopher, founding president',
      'Dakar — West Africa\'s premier francophone hub city',
      'Dakar Rally (formerly — now in Saudi Arabia but Senegal retains the brand)',
      'Teranga — celebrated Senegalese hospitality culture',
      'Offshore oil and gas (transformational new sector)',
      'Wrestling (laamb) — the national sport',
    ],
    challenges: [
      'Youth unemployment and emigration pressure',
      'Dependence on France (CFA franc, institutional ties)',
      'Casamance separatist conflict (low level but persistent)',
      'Governance of new oil and gas revenues',
      'Climate vulnerability — coastal erosion, Sahel drought',
      'Over-fishing of coastal waters (largely by foreign fleets)',
    ],
    resources: [
      'Offshore oil and gas (Sangomar, GTA)',
      'Phosphates (major fertiliser export)',
      'Fishing (Atlantic coast)',
      'Groundnuts and cashews',
      'Tourism (beaches, Dakar, St-Louis heritage)',
      'Zircon and ilmenite (mineral sands)',
    ],
  },

  EGY: {
    iso3: 'EGY',
    history: `Egypt is one of the world's oldest civilisations, with a continuous history spanning over 5,000 years. Ancient Egypt — builder of the Pyramids of Giza, the Sphinx, and the Luxor temples — was a cornerstone of Mediterranean antiquity. Egypt was ruled by the Ptolemaic dynasty (during which Cleopatra reigned), the Roman Empire, Byzantine rule, and from 641 AD by Arab Muslim rulers, followed by Ottoman control from 1517. Modern Egypt was shaped by Muhammad Ali in the early 19th century. Britain occupied Egypt in 1882. Independence came in 1922, and real sovereignty came after the 1952 revolution led by the Free Officers Movement and Gamal Abdel Nasser. Egypt fought wars with Israel in 1948, 1956, 1967, and 1973. The Camp David Accords (1978) brought peace with Israel. Egypt's 2011 Arab Spring revolution ousted President Hosni Mubarak after 30 years. A brief period of elected civilian rule under Mohamed Morsi ended in a 2013 military coup led by General Abdel Fattah el-Sisi, who has governed since.`,
    current: `Egypt is the most populous Arab country (~105 million) and North Africa's largest economy. President el-Sisi faces severe economic pressures: foreign debt has surged to over $160bn, the Egyptian pound has lost more than 60% of its value since 2022, and inflation exceeded 35%. An IMF programme provides a financial lifeline. The Suez Canal is a critical source of foreign exchange (~$10bn annually) — though Houthi attacks in the Red Sea have reduced canal revenues since late 2023. Egypt plays a pivotal regional diplomatic role, particularly in mediating the Israel-Gaza conflict.`,
    economy: `Egypt's GDP (~$400bn) is the largest in North Africa. Key pillars: Suez Canal revenues, remittances from Egyptians abroad (~$28bn/yr), tourism, natural gas exports (Zohr offshore field), and agriculture (Nile Delta). The country is diversifying through manufacturing and the new administrative capital. High inflation, currency depreciation, and debt servicing costs are structural pressures under the IMF-supported reform programme.`,
    knownFor: ['Pyramids of Giza and the Great Sphinx', 'Suez Canal — critical global shipping route', 'Cairo — Africa\'s most populous city', 'Ancient Egyptian civilisation and Pharaonic heritage', 'Largest Arab country by population', 'Arab Spring 2011 — Tahrir Square', 'Zohr offshore natural gas field'],
    challenges: ['Severe debt burden and currency crisis', 'Youth unemployment and population growth', 'Political restrictions on civil society', 'Nile water security (GERD tensions with Ethiopia)', 'Sinai Peninsula security issues', 'Suez Canal and tourism revenue dependence'],
    resources: ['Suez Canal revenues', 'Natural gas (Zohr field)', 'Tourism (Luxor, Cairo, Sinai)', 'Nile Delta agriculture (cotton, rice)', 'Phosphate and gold mining', 'Diaspora remittances'],
  },

  MAR: {
    iso3: 'MAR',
    history: `Morocco has been inhabited for at least 300,000 years. The indigenous Amazigh (Berber) peoples predate Arab settlement. Morocco was part of the Almoravid and Almohad empires, which at their peak controlled much of North Africa and Iberia. The Alaouite dynasty — the current dynasty — has governed since the 17th century. France and Spain established protectorates in 1912. Independence was achieved in 1956 under King Mohammed V. King Hassan II controversially claimed Western Sahara in the "Green March" of 1975. The current king, Mohammed VI, has ruled since 1999 pursuing modernisation and economic liberalisation. Morocco normalised relations with Israel in 2020 in exchange for US recognition of its sovereignty over Western Sahara.`,
    current: `Morocco is one of Africa's most politically stable and economically open countries. Casablanca is the continent's second-largest financial centre. Morocco is the largest African investor in sub-Saharan Africa and has ambitious renewable energy targets — 52% of electricity from renewables by 2030. The 2023 Marrakech earthquake (6.8 magnitude) killed over 2,900 people. Morocco is co-hosting the 2030 FIFA World Cup with Spain and Portugal and is deepening its role as Africa-Europe bridge.`,
    economy: `Morocco's GDP (~$140bn) is driven by phosphate exports (world's largest phosphate reserves, held by OCP Group), tourism, remittances, automotive and aerospace manufacturing, and agriculture. The OCP Group is Africa's most valuable company. Casablanca is francophone Africa's top financial hub. Morocco is investing heavily in solar energy — Noor Ouarzazate is one of the world's largest solar complexes. Green hydrogen export ambitions are growing.`,
    knownFor: ['World\'s largest phosphate reserves (75% of global total)', 'Casablanca — Africa\'s second-largest financial centre', 'Noor Ouarzazate mega-solar complex', 'Marrakech, Fès, Rabat UNESCO medinas', 'Renault and Stellantis automotive hub', 'Co-hosting 2030 FIFA World Cup', 'OCP Group — Africa\'s most valuable company'],
    challenges: ['Western Sahara sovereignty dispute', 'Youth unemployment outside major cities', 'Water scarcity and drought', 'Urban-rural inequality', 'Phosphate revenue dependence', 'Migration transit pressure'],
    resources: ['Phosphate rock (world\'s largest reserves)', 'Solar energy (Sahara potential)', 'Tourism (Marrakech, Fès, Atlantic coast)', 'Automotive manufacturing', 'Agriculture: citrus, olives, argan oil', 'Green hydrogen potential'],
  },

  DZA: {
    iso3: 'DZA',
    history: `Algeria is Africa's largest country by area. The indigenous Amazigh (Berber) people have inhabited the region for millennia. France colonised Algeria in 1830 in one of Africa's most brutal colonial experiences — over one million Europeans settled as colons. The Algerian War of Independence (1954–1962) killed an estimated 300,000–1.5 million Algerians. Independence was won in 1962 under the FLN. The army cancelled elections in 1992 when Islamists were poised to win, triggering a brutal civil war (Black Decade, 1991–2002) that killed up to 200,000 people. Abdelaziz Bouteflika ruled for 20 years until forced out by the Hirak protest movement in 2019.`,
    current: `Algeria is governed by President Tebboune (re-elected 2024), backed by the military establishment. The country is a major natural gas exporter to Europe, with revenues building large foreign currency reserves (~$70bn). Relations with Morocco are deeply strained — borders closed, diplomatic ties cut in 2021. Algeria plays a complex regional role in the Sahel and maintains significant ties with Russia. The Hirak protest movement represents ongoing undercurrents of reform demand.`,
    economy: `Algeria's economy (~$230bn GDP) is heavily dominated by hydrocarbons — oil and gas account for ~95% of export revenues. Sonatrach, the state oil company, is Africa's largest company by revenue. Algeria has the world's 3rd largest shale gas reserves. European gas dependence on Algeria surged after Russia's 2022 Ukraine invasion. Diversification is a priority but faces significant regulatory barriers.`,
    knownFor: ['Africa\'s largest country by area', 'Major natural gas supplier to Europe', 'Algerian War of Independence — landmark decolonisation', 'Sahara Desert (world\'s largest hot desert)', 'Sonatrach — Africa\'s largest company by revenue', 'World\'s 3rd largest shale gas reserves', 'Roman ruins — Timgad, Djémila (UNESCO)'],
    challenges: ['Hydrocarbon revenue dependence', 'High youth unemployment (~30%)', 'Political restrictions', 'Lack of economic diversification', 'Morocco border tensions', 'Water scarcity in southern regions'],
    resources: ['Natural gas (major European supplier)', 'Oil (Hassi Messaoud)', 'Shale gas (3rd largest global)', 'Iron ore', 'Agriculture (Tell fertile north)', 'Solar energy potential'],
  },

  UGA: {
    iso3: 'UGA',
    history: `Uganda's pre-colonial history includes powerful kingdoms — Buganda, Bunyoro, Ankole, and Tooro. The British protectorate was established in 1894, and Uganda gained independence on 9 October 1962. General Idi Amin seized power in 1971, expelled 70,000 Asians, and killed an estimated 100,000–500,000 Ugandans before being removed by a Tanzanian invasion in 1979. Yoweri Museveni's NRM took power in 1986 after years of further instability. Constitutional term limits were removed in 2005 and age limits in 2017, enabling indefinite rule. The Lord's Resistance Army insurgency in northern Uganda (1987–2006), led by Joseph Kony, was one of Africa's most brutal conflicts, abducting thousands of children.`,
    current: `Museveni won a disputed 2021 election against opposition leader Bobi Wine. Uganda enacted one of the world's harshest anti-LGBTQ laws in 2023, drawing international condemnation. Oil production in the Lake Albert basin (East Africa Crude Oil Pipeline) is expected to begin around 2025. Uganda hosts the largest refugee population in Africa — over 1.5 million, primarily from South Sudan and DRC.`,
    economy: `Uganda's economy (~$50bn GDP) is largely agriculture-based. Coffee is the primary export — Uganda is Africa's largest coffee exporter. Tea, cut flowers, fish (Lake Victoria), and sesame are also key exports. Oil reserves in the Albertine Rift are being developed through EACOP — contentious due to environmental concerns. Uganda's tech startup ecosystem is growing rapidly.`,
    knownFor: ['Source of the Nile (Lake Victoria)', 'Mountain gorillas (Bwindi Forest)', '"Pearl of Africa" — Churchill\'s description', 'Largest refugee-hosting country in Africa', 'Africa\'s largest coffee exporter', 'Oil reserves in the Albertine Rift', 'Longest-serving East African leader (Museveni)'],
    challenges: ['Authoritarian governance', 'Anti-LGBTQ legislation and aid suspensions', 'EACOP environmental controversy', 'High population growth', 'Youth unemployment', 'Landlocked — high trade costs'],
    resources: ['Coffee (Africa\'s largest exporter)', 'Oil (Albertine Rift)', 'Tea and tobacco', 'Gold', 'Fisheries (Lake Victoria)', 'Tourism (gorillas, Nile, wildlife)'],
  },

  MOZ: {
    iso3: 'MOZ',
    history: `Mozambique's pre-colonial history includes powerful Swahili coastal city-states central to Indian Ocean trade. Portugal arrived in 1498 and established Mozambique as a key slave and ivory route — one of Africa's longest colonial presences. FRELIMO launched an armed independence struggle in 1964, winning independence on 25 June 1975. A devastating 16-year civil war (1977–1992) between FRELIMO and RENAMO killed ~1 million and displaced 5 million. The 1992 Rome Accords ended the war and Mozambique became a post-conflict reconstruction showcase. Major gas discoveries in the Rovuma Basin (2009–2011) promised transformation, but an Islamist insurgency in Cabo Delgado (since 2017) has disrupted gas projects.`,
    current: `Mozambique faces an active Islamist insurgency in Cabo Delgado (ISIS-Mozambique) that has displaced over 1 million people and halted TotalEnergies' $20bn LNG project. Rwanda and SADC troops have been deployed. Disputed 2024 elections triggered violent protests. Cyclones (Idai, Kenneth, Freddy) have repeatedly devastated the country. The Coral Sul FLNG vessel began LNG exports in 2022 — the first offshore gas exports.`,
    economy: `Mozambique's economy (~$20bn GDP) is agriculture-based (~75% employment) with growing gas exports. Cashews, aluminium (Mozal), coal (Tete), and prawns are primary exports. The Rovuma Basin holds 100+ trillion cubic feet of gas — among the world's largest when fully developed. Extreme poverty persists despite natural resource wealth.`,
    knownFor: ['Some of the world\'s largest offshore gas reserves (Rovuma)', 'Coral Sul — Africa\'s first floating LNG vessel', 'Devastating cyclone impacts', 'Islamist insurgency in Cabo Delgado', 'Cashews and prawns', 'Mozambique Island UNESCO heritage', 'Post-conflict development model (1990s)'],
    challenges: ['Active Islamist insurgency', 'Extreme climate vulnerability', 'Extreme poverty', 'Disputed elections (2024)', 'LNG project delays', 'Debt (tuna bonds scandal)'],
    resources: ['Natural gas (Rovuma Basin)', 'Coal (Tete)', 'Titanium (world\'s largest deposits)', 'Cashews and prawns', 'Hydropower (Cahora Bassa)', 'Tourism (coastline, Gorongosa)'],
  },

  ZMB: {
    iso3: 'ZMB',
    history: `Zambia's Copperbelt was discovered in the 1920s, transforming the British protectorate of Northern Rhodesia. Zambia gained independence on 24 October 1964 under Kenneth Kaunda, who ran a one-party state and nationalised copper mines in 1969. Zambia adopted multiparty democracy in 1991 — one of Africa's earliest transitions — under Frederick Chiluba. Zambia declared itself a Christian nation in 1991. After decades of MMD and PF rule, Hakainde Hichilema of UPND was elected in 2021.`,
    current: `Zambia is navigating a major debt restructuring — it defaulted on Eurobonds in 2020 and reached a restructuring agreement in 2023. President Hichilema is pursuing economic reforms with IMF support. Zambia's copper is strategically critical for the global clean energy transition. Severe load-shedding from drought-reduced hydropower at Kariba Dam is a major economic drag.`,
    economy: `Zambia's economy (~$30bn GDP) depends heavily on copper (~70% of exports). It is Africa's 2nd-largest copper producer with world-class reserves — the clean energy transition creates enormous demand upside. Agriculture employs ~54% of workers. Tourism centred on Victoria Falls is growing. Diversification is a priority.`,
    knownFor: ['Victoria Falls — one of the Seven Natural Wonders', 'Africa\'s 2nd largest copper producer', 'Critical copper supply for clean energy transition', 'First COVID-era African Eurobond default (2020)', 'Kafue and South Luangwa National Parks', 'Kenneth Kaunda — respected founding president', 'Declared Christian nation (1991)'],
    challenges: ['Copper dependence', 'Debt burden and default recovery', 'Severe load-shedding (drought)', 'Youth unemployment', 'Infrastructure gaps', 'Climate vulnerability'],
    resources: ['Copper (world-class)', 'Cobalt and emeralds', 'Hydropower (Kariba, Kafue)', 'Agriculture: maize, tobacco', 'Tourism (Victoria Falls)', 'Uranium deposits'],
  },

  CMR: {
    iso3: 'CMR',
    history: `Cameroon — "Africa in miniature" — has extraordinary geographic and cultural diversity (250+ ethnic groups). Colonised by Germany in 1884, then split between France and Britain after WWI. French Cameroon gained independence on 1 January 1960; British Southern Cameroons joined in 1961. The federation became a unitary state in 1972. Paul Biya has ruled since 1982, making him one of the world's longest-serving leaders. An Anglophone separatist crisis erupted in 2016–2017, escalating into civil conflict (the Ambazonia conflict). Boko Haram operates in the Far North.`,
    current: `Cameroon faces the Anglophone conflict in the Northwest/Southwest, Boko Haram in the Far North, and cross-border tensions. President Biya (aged 91) governs through an entrenched elite. Despite instability, Cameroon hosted the Africa Cup of Nations in 2022. Douala remains the key port for Central African landlocked countries.`,
    economy: `Cameroon's GDP (~$48bn) is the largest in Central Africa. The diversified economy includes cocoa (Africa's 5th-largest producer), oil and gas (declining), timber, and services. Douala is the commercial capital and major port for Chad and CAR. The Kribi deep-sea port is expanding regional capacity.`,
    knownFor: ['"Africa in miniature"', 'Mount Cameroon — highest peak in West/Central Africa', 'Indomitable Lions — multiple AFCON champions', 'Largest Central African economy', 'Major cocoa producer', 'Douala port — Central African gateway', 'Paul Biya — one of world\'s longest-serving leaders'],
    challenges: ['Anglophone separatist conflict', 'Boko Haram in the North', 'Authoritarian governance', 'Declining oil production', 'Anglophone-Francophone tensions', 'Infrastructure deficit'],
    resources: ['Cocoa and coffee', 'Oil and gas', 'Timber (rainforest)', 'Bauxite and iron ore', 'Hydropower', 'Palm oil, bananas, rubber'],
  },

  CIV: {
    iso3: 'CIV',
    history: `Côte d'Ivoire became a French colony in 1893, gaining independence on 7 August 1960. Félix Houphouët-Boigny's 33-year rule (1960–1993) created the "Ivorian miracle" — one of Africa's most prosperous post-independence economies. After his death, political instability and ethnic-regional tensions escalated into a 2002 civil war and a 2010–2011 post-election crisis killing ~3,000 people, ended by French military intervention. Alassane Ouattara has governed since 2011.`,
    current: `Côte d'Ivoire has been one of Africa's fastest-growing economies since 2012 (6–8% annual growth). Political stability is largely restored. The country hosted AFCON 2024. Abidjan is deepening its role as West Africa's economic hub with expanding port infrastructure.`,
    economy: `Côte d'Ivoire's GDP (~$75bn) is the largest in francophone West Africa. It is the world's largest cocoa producer (~45% of global supply). Coffee, rubber, cashews, and palm oil are also major exports. Abidjan is the largest West African port and a key financial centre. The country has offshore oil and gas. A young population (60% under 25) is both opportunity and challenge.`,
    knownFor: ['World\'s largest cocoa producer (~45% of global supply)', 'Abidjan — economic capital of francophone Africa', '"Ivorian miracle" — post-independence prosperity', 'Largest West African port', 'AFCON 2024 host', 'Fastest-growing large African economy since 2012', 'Cashew production (world top 3)'],
    challenges: ['Cocoa dependence and deforestation', 'Cocoa child labour concerns', 'North-south ethnic divisions', 'Third-term presidential controversy', 'Inequality', 'Proximity to Sahel instability'],
    resources: ['Cocoa (world\'s largest)', 'Coffee, cashews, palm oil, rubber', 'Offshore oil and gas', 'Gold', 'Manganese and iron ore', 'Abidjan port and financial hub'],
  },

  AGO: {
    iso3: 'AGO',
    history: `Angola's pre-colonial history includes the powerful Kingdom of Kongo. Portugal colonised Angola and ran the largest Atlantic slave trade operation — an estimated 5+ million Angolans were enslaved. Independence in 1975 triggered a 27-year civil war between the MPLA (Cuban/Soviet-backed) and UNITA (US/South Africa-backed), killing ~1 million. José Eduardo dos Santos ruled for 38 years (1979–2017). President João Lourenço has led since 2017, launching an anti-corruption drive prosecuting dos Santos' children.`,
    current: `Angola is one of Africa's largest oil producers with the continent's third-largest GDP. Lourenço has pursued diversification and anti-corruption reforms, including prosecuting former first family members. Angola restructured substantial Chinese debt and secured IMF support. The US views Angola as a key strategic partner, particularly for critical minerals. The 2022 election saw UNITA win 44% — the closest contest since independence.`,
    economy: `Angola's economy (~$90bn) is dominated by oil and gas (~95% of exports). It is sub-Saharan Africa's 2nd-largest oil producer. Declining oil production drives diversification into agriculture, diamonds (world top-10), and construction. Inga Falls on the Congo River has the world's largest untapped hydropower potential.`,
    knownFor: ['Sub-Saharan Africa\'s 2nd-largest oil producer', 'Kingdom of Kongo — powerful pre-colonial state', 'Largest Atlantic slave trade source', '27-year civil war', 'Inga Falls — world\'s largest hydropower potential', 'Diamond production (world top-10)', 'Luanda — formerly world\'s most expensive expat city'],
    challenges: ['Oil dependence and production decline', 'Extreme inequality', 'Infrastructure deficit', 'Corruption legacy', 'Land mines (civil war)', 'Chinese debt burden'],
    resources: ['Oil and natural gas', 'Diamonds (Lunda provinces)', 'Iron ore, manganese, copper', 'Agriculture: coffee, tobacco', 'Hydropower (Inga Falls)', 'Rare earth minerals'],
  },

  COD: {
    iso3: 'COD',
    history: `The DRC has one of the most painful modern histories. King Leopold II's Congo Free State (1885–1908) was a forced labour camp for rubber extraction — an estimated 10 million Congolese died. Prime Minister Patrice Lumumba was assassinated in 1961 with CIA and Belgian involvement. General Mobutu Sese Seko ruled for 32 years through kleptocracy, renaming the country Zaire. The Second Congo War (1998–2003) — "Africa's World War" involving nine countries — killed ~5.4 million. The conflict in eastern DRC has never fully ended. Félix Tshisekedi became president in 2018 in the first peaceful power transfer in Congolese history.`,
    current: `The DRC is the world's largest French-speaking country by population (~100M). The M23 rebel group (alleged Rwandan backing) captured Goma in early 2025, creating a major humanitarian crisis. The DRC holds the world's largest cobalt reserves — essential for EV batteries — making it a globally strategic actor in the clean energy transition. The government is assertively renegotiating mining contracts.`,
    economy: `The DRC's GDP (~$65bn) masks extreme poverty (~$600 per capita). Mining dominates: cobalt (~70% of global supply), copper, coltan, gold, and diamonds. Inga Falls has the world's largest hydropower potential. Agriculture employs ~70% of workers. Chinese companies dominate mining. The clean energy transition makes DRC's minerals globally critical.`,
    knownFor: ['World\'s largest cobalt reserves (~70% of global supply)', 'Congo River — world\'s deepest river', 'Inga Falls — largest untapped hydropower potential', 'Congo Rainforest — world\'s 2nd largest', 'Most biodiverse country in Africa', 'Leopold II\'s Congo Free State atrocities', 'Mountain gorillas (Virunga)'],
    challenges: ['Ongoing conflict in eastern DRC (M23)', 'Extreme poverty despite resource wealth', 'Governance failure', 'Cobalt child labour', 'Largest African humanitarian crisis', 'Infrastructure collapse'],
    resources: ['Cobalt (world\'s largest)', 'Copper, lithium, coltan', 'Gold and diamonds', 'Congo River hydropower (Inga)', 'Congo Rainforest', 'Agricultural potential'],
  },

  TUN: {
    iso3: 'TUN',
    history: `Tunisia has one of the Mediterranean's most layered histories. Carthage (founded ~814 BC by Phoenicians) was a major power before Rome destroyed it in 146 BC. The Arab conquest in the 7th century brought Islam. France established a protectorate in 1881. Independence came in 1956 under Habib Bourguiba, who granted women the right to divorce, banned polygamy, and guaranteed abortion rights — the Personal Status Code (1956) remains among the Arab world's most progressive. Ben Ali ruled from 1987 until the 2011 Arab Spring revolution, when street vendor Mohamed Bouazizi's self-immolation triggered uprisings across the Arab world. Tunisia's democratic transition won a Nobel Peace Prize in 2015 (National Dialogue Quartet).`,
    current: `Tunisia's democratic transition was reversed when President Kais Saied suspended parliament and seized emergency powers in 2021, pushing through a new constitution in 2022 that concentrated power in the presidency. Tunisia faces severe economic difficulties: debt >90% of GDP, stalled IMF negotiations, high youth unemployment (~35%), and significant Mediterranean boat migration. Despite political regression, Tunisia maintains relatively high human development indicators.`,
    economy: `Tunisia's GDP (~$47bn) is driven by tourism, olive oil (world's 2nd largest exporter), phosphates, automotive components, and textiles. Tunisia is integrated into European automotive supply chains. The economy has been stagnant since 2011, hampered by political instability and the 2015 terrorist attacks that devastated tourism.`,
    knownFor: ['Birthplace of the Arab Spring (2010–2011)', 'One of Arab world\'s most progressive women\'s rights frameworks', 'Ancient Carthage', 'World\'s 2nd largest olive oil exporter', 'Nobel Peace Prize 2015', 'Highest literacy rate in Africa (~85%)', 'Roman ruins: El Jem, Dougga (UNESCO)'],
    challenges: ['Democratic backsliding', 'High public debt and IMF stalemate', 'Youth unemployment and brain drain', 'Mediterranean boat migration', 'Terrorism legacy', 'Economic stagnation since 2011'],
    resources: ['Olive oil (world\'s 2nd largest exporter)', 'Phosphates', 'Tourism (Carthage, Sahara, Djerba)', 'Automotive components', 'Textiles', 'Skilled workforce'],
  },

  MDG: {
    iso3: 'MDG',
    history: `Madagascar is one of the world's most unique countries — an island the size of France with 90% endemic species, first settled by Austronesian peoples from Borneo (~350 BCE), giving Malagasy people uniquely Southeast Asian-African ancestry. Arab traders arrived in the 9th century. The Merina Kingdom unified much of Madagascar by the early 19th century before French colonisation in 1896. Independence came on 26 June 1960. Post-independence history has been turbulent: multiple coups, and a 2009 crisis when Andry Rajoelina (former Antananarivo mayor) ousted Marc Ravalomanana in a military-backed takeover. Rajoelina won elections in 2018 and 2023.`,
    current: `Madagascar is one of the world's poorest countries — over 75% live below the $2.15/day poverty line — despite extraordinary biodiversity and natural resources. Cyclones are frequent and devastating (Batsirai 2022, Freddy 2023). A locust plague and years of drought have caused famine in the south. Political tensions remain. The country's unique biodiversity makes eco-tourism a major growth opportunity.`,
    economy: `Madagascar's GDP (~$15bn) is driven by vanilla (world's largest producer — ~80% of global supply), cloves, coffee, mining (nickel/cobalt at Ambatovy, chromite, ilmenite), and textiles (AGOA beneficiary). Eco-tourism has significant potential. Subsistence agriculture employs ~80% of the workforce. Deforestation threatens both biodiversity and agriculture.`,
    knownFor: ['World\'s 4th largest island — unique biodiversity laboratory', '90% endemic species (lemurs, baobabs, chameleons)', 'World\'s largest vanilla producer (~80% of global supply)', 'Austronesian-African mixed origins', 'Avenue of the Baobabs', 'World\'s highest poverty in non-conflict country', 'Eco-tourism: Lemur Park, Tsingy de Bemaraha'],
    challenges: ['Extreme poverty (>75% below $2.15/day)', 'Extreme climate vulnerability', 'Deforestation and biodiversity loss', 'Political instability', 'Famine in the south', 'Informal sapphire mining'],
    resources: ['Vanilla (world\'s largest producer)', 'Nickel and cobalt (Ambatovy)', 'Ilmenite and chromite', 'Eco-tourism', 'Cloves and coffee', 'Sapphires and gemstones'],
  },
}

