export interface CountryEducation {
  iso3: string
  history: string
  current: string
  economy: string
  knownFor: string[]
  challenges: string[]
  resources: string[]
}

export const COUNTRY_EDUCATION: Record<string, CountryEducation> = {
  KEN: {
    iso3: 'KEN',
    history: `Kenya's modern history begins with British colonisation in the late 19th century, formally declared a Crown Colony in 1920. The Mau Mau uprising (1952–1960) was a pivotal armed resistance movement against colonial rule that accelerated independence. Kenya gained independence on 12 December 1963, with Jomo Kenyatta as its first Prime Minister and later President. The post-independence era saw economic growth alongside political consolidation under KANU party dominance. Multiparty democracy was restored in 1991, followed by a landmark peaceful transition of power in 2002. Kenya's 2007–08 post-election violence, which killed over 1,000 people and displaced hundreds of thousands, led to a power-sharing agreement and constitutional reforms — culminating in a new constitution in 2010 that devolved significant power to 47 counties.`,
    current: `Kenya is East Africa's economic and financial hub, with one of the continent's most diversified and services-driven economies. Nairobi hosts the UN Environment Programme and UN-Habitat headquarters, reflecting its regional significance. The country has a vibrant tech startup ecosystem — dubbed "Silicon Savannah" — led by hubs like iHub. President William Ruto, elected in 2022, has championed a "bottom-up economic model" focused on the informal sector and SME growth. Kenya faces ongoing fiscal pressures with high public debt, and experienced significant anti-government protests in 2024 over proposed tax hikes, which the government subsequently withdrew.`,
    economy: `Kenya's GDP (~$120bn, 2024) is the largest in East and Central Africa. Services dominate at ~50% of GDP, led by finance, telecoms, and retail. Agriculture employs ~40% of the workforce; tea, coffee, cut flowers, and horticultural produce are the main exports. Tourism is a major foreign exchange earner. M-Pesa, launched by Safaricom in 2007, is Kenya's globally acclaimed mobile money platform, now used by 30M+ customers. Kenya is a net energy importer but has significant geothermal capacity — generating ~45% of its electricity from geothermal sources, making it one of the world's leading geothermal producers.`,
    knownFor: [
      'M-Pesa — the world\'s most successful mobile money platform',
      'Silicon Savannah tech startup ecosystem',
      'Nairobi as East Africa\'s financial and logistics hub',
      'World-class long-distance runners (Olympic and marathon champions)',
      'Masai Mara wildlife reserve and safari tourism',
      'Cut-flower exports — the world\'s third largest',
      'Geothermal energy leadership',
    ],
    challenges: [
      'High and rising public debt (>70% of GDP)',
      'Youth unemployment (~30%) despite strong GDP growth',
      'Inequality — Nairobi\'s Kibera is one of Africa\'s largest informal settlements',
      'Climate vulnerability — erratic rainfall affecting agriculture',
      'Corruption and governance quality concerns',
      'Security pressures from Al-Shabaab in the north',
    ],
    resources: [
      'Tea and coffee (primary agricultural exports)',
      'Geothermal energy (Olkaria fields)',
      'Titanium and soda ash mining',
      'Horticulture and cut flowers',
      'Tourism (wildlife, beaches, Great Rift Valley)',
      'Financial and logistics services for East Africa',
    ],
  },

  NGA: {
    iso3: 'NGA',
    history: `Nigeria's pre-colonial history includes powerful states and empires — the Benin Kingdom, Kanem-Bornu, and the Sokoto Caliphate. British colonisation began in the late 19th century and the country was amalgamated as a single administrative unit in 1914. Independence was gained on 1 October 1960, with a federal structure reflecting Nigeria's extraordinary ethnic and religious diversity (250+ ethnic groups; predominantly Muslim north, predominantly Christian south). A devastating civil war (the Biafra War, 1967–70) resulted in over one million deaths. Military coups dominated the next three decades, punctuated by short civilian interludes. Democratic civilian rule was re-established in 1999 and has continued unbroken since, with peaceful transfers of power in 2015 and 2023 — significant milestones in Africa's democratic record.`,
    current: `Nigeria is Africa's most populous nation (~220 million people) and largest economy by nominal GDP. It is the continent's biggest oil producer and a major player in global energy markets. President Bola Tinubu, inaugurated in May 2023, initiated significant economic reforms — removing the longstanding petrol subsidy and unifying the foreign exchange rate — which triggered sharp inflation and currency depreciation in the near term. The north faces serious security challenges: Boko Haram/ISWAP insurgency in the northeast, banditry in the northwest, and farmer-herder conflicts in the Middle Belt. The southeast sees periodic separatist agitation. Despite these pressures, Lagos remains Africa's most dynamic commercial city and startup hub.`,
    economy: `Nigeria's GDP (~$500bn, nominal) is Africa's largest, driven heavily by oil and gas (~90% of foreign exchange earnings). However, the oil sector employs only ~4% of the workforce — agriculture (employing ~36%) and services dominate actual economic activity. The informal economy is enormous, estimated at 57% of GDP. Lagos is home to Africa's most valuable tech startup ecosystem, including unicorns Flutterwave, Paystack (acquired by Stripe), and Interswitch. Nollywood — Nigeria's film industry — is the world's second-largest by volume and generates ~$1bn+ annually. Nigeria is a major exporter of cocoa and sesame seeds.`,
    knownFor: [
      'Africa\'s largest economy and most populous nation',
      'Oil and gas production (Niger Delta)',
      'Nollywood — the world\'s second largest film industry',
      'Africa\'s leading tech startup ecosystem (Lagos)',
      'Afrobeats music — global cultural influence',
      'Largest diaspora remittance recipient in Africa (~$20bn/yr)',
      'Diversity — over 250 ethnic groups and languages',
    ],
    challenges: [
      'Oil dependence and revenue volatility',
      'Boko Haram/ISWAP insurgency in the northeast',
      'Extreme inequality — a third of population in extreme poverty',
      'Infrastructure deficit (power, roads)',
      'Currency and inflation pressures post-2023 reforms',
      'Security: banditry, kidnapping, and communal violence',
    ],
    resources: [
      'Crude oil (Niger Delta) — Africa\'s largest reserves',
      'Natural gas (significant LNG export infrastructure)',
      'Agriculture: cocoa, sesame, groundnuts, palm oil',
      'Solid minerals: coal, iron ore, tin, limestone',
      'Bitumen deposits (largest in the world)',
      'Fisheries and maritime resources',
    ],
  },

  ETH: {
    iso3: 'ETH',
    history: `Ethiopia is one of the world's oldest nations and the only African country to have successfully resisted European colonisation — defeating Italy at the Battle of Adwa in 1896. The ancient Aksumite Empire (1st–7th century AD) was a major trading power; the Solomonic dynasty, claiming descent from King Solomon and the Queen of Sheba, ruled for centuries. Emperor Haile Selassie ruled from 1930 until a Marxist military junta (the Derg) deposed him in 1974. The Derg's brutal rule ended in 1991 when the Ethiopian People's Revolutionary Democratic Front (EPRDF) took power. The EPRDF implemented an ethnic federalism system across nine regional states. Prime Minister Abiy Ahmed came to power in 2018, winning the Nobel Peace Prize in 2019 for the Ethiopia-Eritrea peace deal. A devastating civil war in the Tigray region (2020–2022) killed hundreds of thousands and created one of the world's worst humanitarian crises.`,
    current: `Ethiopia is Africa's second most populous country (~125 million) and one of the continent's fastest-growing economies over the past decade. The country faces significant post-war reconstruction challenges in Tigray, Afar, and Amhara regions. Conflict has also spread to other areas, with Amhara regional forces clashing with federal troops since 2023. Despite these conflicts, Addis Ababa remains the diplomatic capital of Africa, hosting the African Union headquarters. Ethiopia is pursuing an ambitious industrialisation agenda through industrial parks and manufacturing investment, and has significant hydropower ambitions with the Grand Ethiopian Renaissance Dam (GERD) on the Nile.`,
    economy: `Ethiopia's economy is among Africa's fastest-growing, though it remains largely agriculture-based (~35% of GDP, ~70% of employment). Coffee is Ethiopia's most iconic export and cultural institution — it is the birthplace of coffee. Ethiopia is Africa's largest coffee producer. Flowers and vegetables are growing export industries. The government has pursued state-led industrialisation through large public investments and Chinese-financed infrastructure. The Grand Ethiopian Renaissance Dam, now partially operational, will make Ethiopia a major electricity exporter. Inflation has been a persistent challenge, exceeding 30% at times. Ethiopia joined the African Continental Free Trade Area and is seeking full WTO membership.`,
    knownFor: [
      'The only African nation to defeat a European colonial power (Battle of Adwa, 1896)',
      'Birthplace of coffee — Kaffa region',
      'The African Union headquarters (Addis Ababa)',
      'Ancient Aksumite civilisation and Orthodox Christianity',
      'Lucy — the 3.2 million year old hominin fossil found in Ethiopia',
      'Long-distance running — Olympic champions for six decades',
      'Grand Ethiopian Renaissance Dam (largest in Africa)',
    ],
    challenges: [
      'Ongoing armed conflicts in multiple regions',
      'One of the world\'s largest humanitarian crises (post-Tigray war)',
      'Landlocked status following Eritrean independence',
      'High inflation and hard currency shortages',
      'Climate vulnerability — droughts affecting food security',
      'Extreme poverty in rural areas',
    ],
    resources: [
      'Coffee (primary export, cultural identity)',
      'Hydropower (Blue Nile, GERD)',
      'Agriculture: teff, sesame, flowers, pulses',
      'Gold and tantalum mining',
      'Geothermal energy potential (Rift Valley)',
      'Livestock (Africa\'s largest livestock population)',
    ],
  },

  GHA: {
    iso3: 'GHA',
    history: `Ghana was the first sub-Saharan African country to gain independence from colonial rule, on 6 March 1957, led by Kwame Nkrumah — a pan-Africanist icon. The Gold Coast, as it was known under British rule, was so named for its historic role in the Atlantic gold trade. Ghana also played a central role in the transatlantic slave trade — Elmina and Cape Coast castles remain powerful historical sites. After independence, Nkrumah's socialist-led government was overthrown in a 1966 coup. A cycle of military and civilian governments followed until the Fourth Republic was established in 1993. Ghana is widely regarded as one of West Africa's most politically stable democracies, with consistent peaceful transfers of power since 1992. It served as a symbol of democratic maturity when opposition candidate John Atta Mills defeated the incumbent in 2008.`,
    current: `Ghana is considered one of West Africa's most stable and open economies and democracies. John Mahama won the 2024 presidential election, returning to power with a mandate focused on economic recovery. Ghana experienced a severe economic crisis in 2022–23 — inflation peaked at ~54%, the cedi lost ~60% of its value, and the country defaulted on external debt for the first time, seeking IMF support. A debt restructuring process is underway. Despite the fiscal crisis, Ghana's institutions held — there was no breakdown of democracy or social order. Oil was discovered offshore in 2007 (Jubilee Field) and production began in 2010, diversifying the economy.`,
    economy: `Ghana's economy (~$75bn GDP) is diversified relative to its neighbours — driven by gold, oil, cocoa, and growing services. It was the world's second-largest cocoa producer for many years. Gold mining employs hundreds of thousands and is a major foreign exchange earner. Offshore oil and gas production (from the Jubilee, TEN, and Sankofa fields) contributes ~20% of government revenue. Ghana has a relatively developed financial sector and a growing technology and fintech scene in Accra. It is the leading exporter of cashew nuts in West Africa. Tourism is growing, with the "Year of Return" campaign (2019) attracting the African diaspora.`,
    knownFor: [
      'First sub-Saharan country to gain independence (1957)',
      'Kwame Nkrumah — pan-African icon',
      'Gold and cocoa — historic "Gold Coast" export economy',
      'One of West Africa\'s most stable democracies',
      '"Year of Return" — major diaspora tourism campaign',
      'Cape Coast and Elmina slave trade castles',
      'Kente cloth — iconic woven textile tradition',
    ],
    challenges: [
      'Debt crisis and IMF programme (2022–23)',
      'High inflation and currency depreciation',
      'Over-dependence on commodity exports (gold, cocoa, oil)',
      'Illegal gold mining (galamsey) causing environmental damage',
      'Youth unemployment and graduate underemployment',
      'Infrastructure gaps outside Accra-Kumasi corridor',
    ],
    resources: [
      'Gold (major mining industry)',
      'Offshore oil and gas (Jubilee, TEN, Sankofa fields)',
      'Cocoa (world top-3 producer)',
      'Cashew nuts and shea butter',
      'Manganese and bauxite',
      'Timber and marine fisheries',
    ],
  },

  ZAF: {
    iso3: 'ZAF',
    history: `South Africa's history is defined by its complex layering of indigenous kingdoms, Dutch and British colonisation, and the apartheid system (1948–1994). The Dutch East India Company established a settlement at the Cape in 1652. The discovery of diamonds (1867) and gold (1886) transformed the region, fuelling the Anglo-Boer Wars. The apartheid regime — a system of legislated racial segregation and oppression — was formally institutionalised in 1948 by the National Party. The African National Congress (ANC), founded in 1912, led the liberation struggle, with figures such as Nelson Mandela, Walter Sisulu, and Oliver Tambo. Mandela spent 27 years in prison before his release in 1990. South Africa transitioned peacefully to democracy in 1994, with Mandela becoming the country's first democratically elected president — hailed globally as a miracle of reconciliation.`,
    current: `South Africa is Africa's most industrialised economy and its second-largest by GDP. It faces deep structural challenges: 32% unemployment (60%+ among youth), extreme inequality (one of the world's highest Gini coefficients), persistent load-shedding (rolling blackouts), high crime rates, and weakening state institutions. The ANC, which has governed since 1994, lost its parliamentary majority for the first time in May 2024 elections, forming a Government of National Unity with the Democratic Alliance and other parties. This political shift is being watched closely as a test of South Africa's democratic resilience. The country has one of Africa's most sophisticated financial markets and capital market infrastructure.`,
    economy: `South Africa's GDP (~$400bn) is the continent's second largest. The economy is diversified: mining (gold, platinum, coal, diamonds), manufacturing, financial services, retail, and agriculture. South Africa is the world's largest producer of platinum and chrome, and a top producer of gold, manganese, and vanadium. Johannesburg is Africa's financial capital. The automotive sector (BMW, Mercedes, Toyota all have manufacturing plants) is a significant industrial pillar. Severe energy shortages — Eskom's load-shedding — have cost an estimated 2–3% of GDP annually. Tourism is recovering post-COVID, drawn by the Cape region, wildlife, and wine industry.`,
    knownFor: [
      'Nelson Mandela and the end of apartheid',
      'World\'s largest platinum producer',
      'The Cape Winelands and Cape of Good Hope',
      'Kruger National Park and the Big Five',
      'Johannesburg as Africa\'s financial capital',
      'Rugby and cricket — consistent world-class performance',
      'Constitutional democracy with strong rights protections',
    ],
    challenges: [
      'One of the world\'s highest unemployment rates (~32%)',
      'Extreme inequality (Gini coefficient >0.60)',
      'Eskom load-shedding and energy crisis',
      'Very high rates of violent crime',
      'Corruption and state capture aftermath',
      'Skills emigration ("brain drain")',
    ],
    resources: [
      'Platinum group metals (world\'s largest reserves)',
      'Gold (Witwatersrand Basin)',
      'Coal (major electricity generation and export)',
      'Diamonds (Kimberley)',
      'Manganese, chromium, vanadium',
      'Agriculture: wine, citrus, maize, sugar',
    ],
  },

  TZA: {
    iso3: 'TZA',
    history: `Tanzania was formed in 1964 by the union of Tanganyika (independent 1961) and Zanzibar (independent 1963). Tanganyika was led to independence by Julius Nyerere, one of Africa's most respected leaders. Nyerere's socialist ujamaa ("familyhood") policy — including forced villagisation — had mixed results economically but promoted national unity and literacy. Zanzibar, with its Arab-Swahili history as a former Sultanate and hub of the Indian Ocean trade (and slave trade), maintains a distinct semi-autonomous identity within the union. Tanzania was the first East African country to abolish colonial-era wildlife hunting reserves and create national parks. The country maintained stability and peace throughout the Cold War era, hosting liberation movements from neighbouring countries. President Samia Suluhu Hassan, who took office in 2021 following the death of President John Magufuli, became Africa's first female head of state and has pursued a notably more open and reform-oriented approach.`,
    current: `Tanzania is East Africa's second-largest economy and among the continent's most politically stable nations. Under President Samia, Tanzania has re-engaged with international partners after a period of isolation, rejoined the East African Community's integration process, and taken a more pragmatic approach to foreign investment. The country is a leading destination for safari tourism (Serengeti, Ngorongoro) and has major new gas reserves offshore. A large-scale infrastructure push — including Standard Gauge Railway — is underway. Zanzibar is growing as a high-end tourism destination and has aspirations to become an Islamic finance hub.`,
    economy: `Tanzania's GDP (~$85bn) is driven by agriculture (~25% of GDP, ~65% of employment), tourism, and mining. Gold is the largest export earner; Tanzania is among Africa's top gold producers. Coffee, tea, cotton, cashews, and tobacco are key agricultural exports. Major natural gas discoveries offshore (the Ruvuma Basin holds some of East Africa's largest reserves) could transform the economy once an LNG export terminal is built — a project under negotiation with international energy companies. Tourism centres on the Serengeti, Ngorongoro Crater, Kilimanjaro, and Zanzibar beaches. Tanzania benefits from being an AGOA beneficiary for textile exports.`,
    knownFor: [
      'Serengeti — home to the Great Migration, the world\'s largest animal movement',
      'Mount Kilimanjaro — Africa\'s highest peak',
      'Zanzibar — spice island, ancient trading history',
      'Julius Nyerere — one of Africa\'s most revered leaders',
      'Ngorongoro Crater — world\'s largest intact volcanic caldera',
      'Significant offshore natural gas reserves',
      'Swahili language — Africa\'s most widely spoken indigenous language',
    ],
    challenges: [
      'Dependence on rain-fed agriculture and climate vulnerability',
      'Infrastructure gaps outside Dar es Salaam',
      'Semi-autonomous Zanzibar political tensions',
      'LNG development delays impacting fiscal projections',
      'Limited industrial diversification',
      'Population growth outpacing service delivery',
    ],
    resources: [
      'Gold (major export)',
      'Natural gas (Ruvuma offshore basin)',
      'Tourism (Serengeti, Kilimanjaro, Zanzibar)',
      'Agriculture: coffee, tea, cashews, sisal',
      'Gemstones: tanzanite (found only in Tanzania)',
      'Hydropower potential',
    ],
  },

  RWA: {
    iso3: 'RWA',
    history: `Rwanda's modern history is indelibly marked by the 1994 genocide, in which an estimated 800,000–1,000,000 Tutsi and moderate Hutu were killed in 100 days — one of the fastest mass killings in recorded history. Colonial powers (first Germany, then Belgium) hardened pre-existing social distinctions between Hutu, Tutsi, and Twa into a racialised hierarchy, laying the groundwork for ethnic violence that began in the lead-up to independence in 1962. The Rwanda Patriotic Front (RPF), a Tutsi-led rebel army led by Paul Kagame, halted the genocide and took control of the country in July 1994. Post-genocide Rwanda embarked on a remarkable reconstruction under Kagame's leadership — prioritising reconciliation (gacaca community courts), national identity over ethnicity, women's empowerment, and a vision of becoming a knowledge and services economy. Rwanda joined the Commonwealth in 2009, despite having no colonial ties to Britain.`,
    current: `Rwanda is often cited as Africa's governance model for its low corruption, clean cities, effectiveness of public service delivery, and gender representation — the parliament has the world's highest share of female legislators (~61%). President Paul Kagame has won re-election with very large majorities; critics point to restrictions on political opposition and press freedom. The country is positioning itself as a regional hub for conferences, finance, and technology — Kigali hosts major international summits and has a world-class convention centre. Rwanda faces pressure from its involvement in eastern DRC, where it is alleged to support the M23 rebel group — a source of significant international tension.`,
    economy: `Rwanda's economy (~$14bn GDP) is small but growing rapidly (~8% per year pre-COVID). Services — particularly tourism, finance, and hospitality — are the fastest-growing sectors. Gorilla trekking in Volcanoes National Park draws high-value, low-volume tourism. Coffee and tea are primary agricultural exports. Rwanda has made significant strides in financial inclusion (through mobile money and banking expansion) and ease of doing business. The country aspires to become the "Singapore of Africa" — a small, efficient, well-governed hub economy. It has attracted investment from major international companies including Volkswagen (vehicle assembly) and Andela. The national carrier, RwandAir, is growing as an African aviation hub.`,
    knownFor: [
      'Fastest post-genocide reconstruction in modern history',
      'World\'s highest share of female parliamentarians (~61%)',
      'Cleanest and safest city in Africa (Kigali)',
      'Mountain gorilla conservation (Volcanoes National Park)',
      'Near-zero tolerance for corruption — consistently top African governance rankings',
      'Umuganda — monthly community work days',
      '"Singapore of Africa" governance ambitions',
    ],
    challenges: [
      'Small, landlocked economy highly dependent on aid',
      'Limited natural resources',
      'Restricted political space and press freedom',
      'Regional tensions over DRC/M23 involvement',
      'High population density (most densely populated mainland African country)',
      'Climate vulnerability — hillside erosion and landslides',
    ],
    resources: [
      'Tourism (gorillas, Lake Kivu, cultural heritage)',
      'Coffee and tea (high-quality specialty exports)',
      'Coltan and cassiterite (conflict mineral challenges)',
      'Methane gas (Lake Kivu — unique energy source)',
      'Human capital and services economy',
      'Financial and logistics hub services',
    ],
  },

  SEN: {
    iso3: 'SEN',
    history: `Senegal has been a crossroads of trans-Saharan trade routes, Islamic scholarship, and Atlantic commerce for centuries. The city of Saint-Louis, founded by the French in 1659, was the first European settlement in sub-Saharan Africa. Senegal gained independence from France on 4 April 1960 under Léopold Sédar Senghor, a poet, philosopher, and one of Africa's most intellectually distinguished leaders — also the first African elected to the Académie française. Senghor voluntarily transferred power to Abdou Diouf in 1980 — a rare act of voluntary presidential transition in Africa at the time. Senegal has maintained unbroken democratic governance since independence, making it one of Africa's most stable countries. The Casamance region in the south has experienced a low-level separatist conflict since 1982, though recent peace agreements have largely held.`,
    current: `Senegal is West Africa's most enduring democracy and a model of political stability — having peacefully transferred power multiple times. In March 2024, Bassirou Diomaye Faye won a historic presidential election, becoming the youngest head of state in Senegalese history (and one of the youngest in Africa) on an anti-corruption and sovereignty platform. Faye and Prime Minister Ousmane Sonko represent a generational shift, with promises to renegotiate natural resource contracts and reduce dependence on France. Senegal is on the cusp of a major economic transformation with large offshore oil and gas reserves (Sangomar field, GTA project) beginning production in 2024 — the first time Senegal will produce hydrocarbons at scale.`,
    economy: `Senegal's GDP (~$30bn) has grown consistently at 5–7% annually. The economy is diversified: remittances (~10% of GDP), services (telecommunications, finance), fishing, phosphate mining, and tourism. Dakar is the most important financial and services hub in francophone West Africa. The CFA franc monetary union ties Senegal's currency to the euro — a source of both stability and debate. Agriculture (groundnuts, millet, sorghum) employs ~60% of the rural population. Offshore oil from the Sangomar field and gas from Greater Tortue Ahmeyim LNG are expected to significantly boost government revenues from 2025 onwards, raising both opportunity and governance challenges.`,
    knownFor: [
      'Africa\'s oldest continuous democracy (independence without military coup)',
      'Léopold Sédar Senghor — poet, philosopher, founding president',
      'Dakar — West Africa\'s premier francophone hub city',
      'Dakar Rally (formerly — now in Saudi Arabia but Senegal retains the brand)',
      'Teranga — celebrated Senegalese hospitality culture',
      'Offshore oil and gas (transformational new sector)',
      'Wrestling (laamb) — the national sport',
    ],
    challenges: [
      'Youth unemployment and emigration pressure',
      'Dependence on France (CFA franc, institutional ties)',
      'Casamance separatist conflict (low level but persistent)',
      'Governance of new oil and gas revenues',
      'Climate vulnerability — coastal erosion, Sahel drought',
      'Over-fishing of coastal waters (largely by foreign fleets)',
    ],
    resources: [
      'Offshore oil and gas (Sangomar, GTA)',
      'Phosphates (major fertiliser export)',
      'Fishing (Atlantic coast)',
      'Groundnuts and cashews',
      'Tourism (beaches, Dakar, St-Louis heritage)',
      'Zircon and ilmenite (mineral sands)',
    ],
  },
}
